# Generated by Django 3.1.3 on 2020-11-23 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_profile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default='z', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='a', max_length=200),
        ),
    ]
