# Generated by Django 3.1.3 on 2020-11-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20201123_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='Email not found', max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, default='o', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, default='o', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(default='j', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='otp',
            field=models.CharField(default='j', max_length=6),
        ),
    ]
