# Generated by Django 3.1.3 on 2020-11-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20201123_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', max_length=2559, upload_to='photos/'),
        ),
    ]
