# Generated by Django 3.1.3 on 2020-11-27 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='username',
            field=models.CharField(default='a', max_length=200),
        ),
    ]
