# Generated by Django 3.1.3 on 2020-11-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_photo_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='CompanyID',
            field=models.CharField(default='a', max_length=20),
        ),
    ]
