# Generated by Django 3.1.3 on 2020-11-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_profile_companyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Activate_Account',
            field=models.BooleanField(default=False),
        ),
    ]
